 - name: /johnny5/left_arm_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
        - l_arm_sh_p1_pos
        - l_arm_sh_r_pos
        - l_arm_sh_p2_pos
        - l_arm_el_y_pos
        - l_arm_wr_r_pos
        - l_arm_wr_y_pos
        - l_arm_wr_p_pos
       
 - name: /johnny5/right_arm_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
        - r_arm_sh_p1_pos
        - r_arm_sh_r_pos
        - r_arm_sh_p2_pos
        - r_arm_el_y_pos
        - r_arm_wr_r_pos
        - r_arm_wr_y_pos
        - r_arm_wr_p_pos
