controller_list:
  - name: fake_r_arm_group_controller
    joints:
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  - name: fake_l_arm_group_controller
    joints:
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
  - name: fake_l_arm_with_torso_group_controller
    joints:
      - torso_y
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
  - name: fake_r_arm_with_torso_group_controller
    joints:
      - torso_y
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  - name: fake_right_hand_controller
    joints:
      - r_f0_j0
      - r_f1_j0
  - name: fake_left_hand_controller
    joints:
      - l_f0_j0
      - l_f1_j0
